const mongoose = require('mongoose');
const requireLogin=require("../middlewares/requireLogin");
const requireCredits = require("../middlewares/requireCredits");
const recipientSchema = require('../models/Recipient');
const Mailer = require('../services/Mailer');
const Survey = mongoose.model('surveys');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');

module.exports = (app) => {

  app.get('/api/surveys/thanks', (req,res) => {
    res.send('Thanks for voting!');
  })
    //create a survey
  app.post('/api/surveys', requireLogin, requireCredits, async (req,res) => {
    const {title, subject, body, recipients } = req.body;
    //create new survey instance
    const survey = new Survey({
        title,
        subject,
        body,
        recipients: recipients.split(',').map(email => {return {email: email.trim()}} ),
        _user: req.user.id, //id generated by mongoose model
        dateSent: Date.now()
    });

    //great place to send an email
    const mailer = new Mailer(survey, surveyTemplate(survey));
    //wait for sending email finish => save survey
    try {
      await mailer.send();
      await survey.save(); //???
      //update user
      req.user.credits -=1;
      const user = await req.user.save();

      res.send(user);
    } catch (err) {
      res.status(422).send(err);
    }


  });  
};