const mongoose = require('mongoose');
const requireLogin=require("../middlewares/requireLogin");
const requireCredits = require("../middlewares/requireCredits");
const recipientSchema = require('../models/Recipient');

const Survey = mongoose.model('surveys');

module.exports = (app) => {
    //create a survey
  app.post('/api/surveys', requireLogin, requireCredits, (req,res) => {
    const {title, subject, body, recipients } = req.body;
    //create new survey instance
    const survey = new Survey({
        title,
        subject,
        body,
        recipients: recipients.split(',').map(email => {return {email: email.trim()}} ),
        _user: req.user.id, //id generated by mongoose model
        dateSent: Date.now()
    })
  });  
};